### ISSUE TITLE
Fix rights on the log file

### ISSUE THREAD

**Issue by bfontaine** [dj-wasabi/ansible-telegraf#195]
Hello,
I’m not sure if this is an issue with my setup or the playbook. On my Ubuntu servers the "Restart Telegraf" step fails because the log file `/var/log/telegraf.log` is not writable by `telegraf`. I tried to fix the issue by creating the file before the role, but I can’t `chown` it to `telegraf` since the user is created by the role.

This is the relevant part of my playbook:
```yaml
- ansible.builtin.include_role:
    name: dj-wasabi.telegraf
  vars:
    telegraf_agent_output:
      - type: influxdb_v2
        config: {} # ...
    telegraf_agent_logfile: "/var/log/telegraf.log"
    telegraf_agent_package_state: latest
    telegraf_plugins_default: [ ]
```

Should there be a way to specify the owner/group of `telegraf_agent_logfile` in this role?
