### ISSUE TITLE
Ability to add multiple times the same extra-plugin

### ISSUE THREAD

**Issue by gaizeror** [dj-wasabi/ansible-telegraf#57]
**Is your feature request related to a problem? Please describe.**
I can't add the same plugin with different config. For example I want to monitor some services with procstat, multiple procstat configs overrides eachother.

**Describe the solution you'd like**
Ability to add many configurations of the same plugin

**Additional context**
Thank you!

**Comment by derlucas** [comment]
Seems to be an issue with the release on ansible galaxy i think.
In the master branch there is already the fix mentioned in #30 
And in the telegraf-extra-plugin.conf.j2 there is the new style "[[inputs.{{ item.value.plugin | default(item.key) }}]]"
When downloading the role via ansible-galaxy, there is an older template. I guess the release on galaxy is too old.

**Comment by dj-wasabi** [comment]
Hi

I'll add a new version to the Galaxy today. Will close this issue once it is added.

**Comment by dj-wasabi** [comment]
I just pushed a version to the Galaxy. Therefor I close this issue.

**Comment by gaizeror** [comment]
@derlucas @dj-wasabi After downloading latest it is yet not working, where am I wrong:
I want to monitor multiple processes with procstat. 
example:

```
    telegraf_plugins_extra:
      procstat:
        config:
          - pattern = "telegraf"
      procstat:
        config:
          - pattern = "sshd"
```
