### ISSUE TITLE
Pin telegraf to {present, latest, specific-version}

### ISSUE THREAD

**Issue by libertyy** [dj-wasabi/ansible-telegraf#59]
The role provides no mechanism to install a specific verison of telegraf. The role does not provide a mechanism to upgrade out of date installs to the latest version

**Describe the solution you'd like**
By default, the role should continue to install with "state = present".  We should be able to pass into the role a "TELEGRAF_VERSION" of either "latest" or to specific version

**Comment by Rylon** [comment]
I would like to +1 this - when using `state: present` or `state: installed`, if the agent is already installed, but a newer version is set in the defaults, no change is made.

Since the version is already set by the variable `telegraf_agent_version`, you could use this to install the specific version, so that it will be upgraded if that variable changes, for example:

```yaml
apt:
  name: "telegraf={{ telegraf_agent_version }}"
  state: present
  notify: "Restart Telegraf"
  become: yes
  force: true
```

Note that adding `force: true` is also required, in order to allow downgrading as well as upgrading.
