### ISSUE TITLE
Daemon crash because of empty config.conf and plugin.conf files.

### ISSUE THREAD

**Issue by tristanbes** [dj-wasabi/ansible-telegraf#63]
**Describe the bug**
Impossible to start the telegraf serivce
Having a simple configuration like 
default config +
```
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["http://influx.foo.com:8086"]
      - database = "telegraf"
      - username = "{{ influx_user }}"
      - password = "{{ influx_password }}"

telegraf_plugins_extra_exclusive: True
telegraf_plugins_extra:
  nginx:
    config:
      - urls = ["http://localhost:9090/nginx_status"]
  phpfpm:
    config:
      - urls = ["http://localhost:9090/fpm-status"]
```

Generates inside `telegraf.d/` folder : 
```
-rw-r----- 1 telegraf telegraf  70 Nov 14 17:47 config.conf
-rw-r----- 1 telegraf telegraf 119 Nov 14 17:56 nginx.conf
-rw-r----- 1 telegraf telegraf 118 Nov 14 17:56 phpfpm.conf
-rw-r----- 1 telegraf telegraf  70 Nov 14 17:47 plugin.conf
```

The problem is that `config.conf` and `plugin.conf` are empty-ish
```
### MANAGED BY dj-wasabi.telegraf ANSIBLE ROLE ###

[[inputs.config]]
```
```
### MANAGED BY dj-wasabi.telegraf ANSIBLE ROLE ###

[[inputs.config]]
```

As long as those two files are present, `telegraf` service won't start/keeps crashing.

Having set `telegraf_plugins_extra_exclusive: True` to true doesn't help either.

**Installation method/version**

* Ansible Galaxy / latest tag available

**Ansible Version**

```
2.7.1
```

**Targetted hosts**
Concerns the following OS(es):
* Debian

**Comment by dj-wasabi** [comment]
Hi,

I tried to replicate this.
I have the following configuration set into my Molecule config:
```
  inventory:
    group_vars:
      all:
        telegraf_plugins_extra_exclusive: True
        telegraf_plugins_extra:
          nginx:
            config:
              - urls = ["http://localhost:9090/nginx_status"]
          phpfpm:
            config:
              - urls = ["http://localhost:9090/fpm-status"]
        telegraf_agent_output:
          - type: influxdb
            config:
              - urls = ["http://influxdb:8086"]
              - database = "telegraf"
              - precision = "s"
        telegraf_plugins_extra:
          percpu-usage:
            plugin: cpu
            config:
              - percpu = true
              - totalcpu = false
              - name_override = "percpu_usage"
              - fielddrop = ["cpu_time*"]
```
No other config, only the above and what is provided in the `default/main.yml`. But I don't see any empty files. Do you have some other configuration set somewhere?

Kind regards,
Werner

**Comment by tristanbes** [comment]
Well, I have:

`all.yml`
```
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["http://influx.yproximite.com:8086"]
      - database = "telegraf"
      - username = "{{ influx_user }}"
      - password = "{{ influx_password }}"

telegraf_plugins_extra: {}
telegraf_plugins_extra_exclusive: True
```

`web.yml`
```
## Monitoring
telegraf_plugins_extra:
  nginx:
    config:
      - urls = ["http://localhost:9090/nginx_status"]
  phpfpm:
    config:
      - urls = ["http://localhost:9090/fpm-status"]
  varnish: ~
```


But I've been using your playbook since ages ago, so maybe it was due to consecutive updates ?
