### ISSUE TITLE
No telegraf_plugin_extra info is added to plugins

### ISSUE THREAD

**Issue by carlba** [dj-wasabi/ansible-telegraf#71]
**Describe the bug**
Given the following usage

```yaml
- name: Setup and install telegraf
  become: true
  include_role:
    name: dj-wasabi.telegraf
  vars:
    telegraf_plugins_extra:
      # https://github.com/influxdata/telegraf/tree/master/plugins/inputs/smart
      - plugin: smart
        config:
          - use_sudo = true
```

I get two files in `/etc/telegraf/telegraf.d` `confing.conf` and `plugin.conf`. The contents of the files are

*config.conf*
```
### MANAGED BY dj-wasabi.telegraf ANSIBLE ROLE ###

[[inputs.config]]
```

*plugins.conf*
```
### MANAGED BY dj-wasabi.telegraf ANSIBLE ROLE ###

[[inputs.plugin]]
```

The plugin extras doesn't seem to be added.

**Installation method/version**
* Role version 0.10.0
* Ansible-galaxy 2.7.1

**Ansible Version**
```
ansible 2.7.1
  config file = /Users/cada/development/ansible-servern/ansible.cfg
  configured module search path = [u'/Users/cada/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/cada/development/ansible-servern/venv/lib/python2.7/site-packages/ansible
  executable location = /Users/cada/development/ansible-servern/venv/bin/ansible
  python version = 2.7.15 (default, Oct  2 2018, 11:42:04) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]

```

**Targetted hosts**
Concerns the following OS(es):
* Ubuntu

**Expected behavior**
I expect the plugins in telegraf_plugins_extra to be added to the plugins config file.
