### ISSUE TITLE
Revise Templates To allow Different Types Of Filters

### ISSUE THREAD

**Issue by zachdesai** [dj-wasabi/ansible-telegraf#91]
**Is your feature request related to a problem? Please describe.**
When using inputs.logparser, I'd like to template applying grok filters - this requires a file which looks like
`
[[inputs.logparser]]

    files = ["/var/log/apache/access.log"]

    from_beginning = False

[inputs.logparser.grok]

    patterns = ["%{COMBINED_LOG_FORMAT}"]

    measurement = "apache_access_log"
`
I'm unsure if this is possible already with this role, but I couldn't figure it out.

**Describe the solution you'd like**
Modify the templates to allow custom 'subplugins' (I don't really know the Telegraf nomenclature) - with this, you could also remove the entries for tags, tagpass, tagdrop parts and pass them as subplugins

This seems to be working for me

`{% if item.value.subplugin is defined and item.value.subplugin is iterable %}

{% for subpluginname in item.value.subplugin %}

[inputs.{{ item.value.plugin | default(item.key) }}.{{ subpluginname }}]

{% for items in item.value.subplugin[subpluginname] %}

    {{ items }}

{% endfor %}

{% endfor %}

{% endif %}
`

**Additional context**

eg group_vars file
    logparser:
      config:
        - files = ["/var/log/apache/access.log"]
        - from_beginning = False
      subplugin:
        grok:
          - patterns = ["%{COMBINED_LOG_FORMAT}"]
          - measurement = "apache_access_log"

**Comment by mcaulifn** [comment]
Found this while searching: https://github.com/jtyr/yaml2toml-converter
Might be helpful for a completely generic template

**Comment by dj-wasabi** [comment]
@mcaulifn  That looks nice, ever worked with it?

**Comment by mcaulifn** [comment]
just found it and then tried it out. there seem to be a few kinks but overall a great start.

```
telegraf_custom_plugins_extra:
  switches:
    inputs.snmp:
      agents:
        - 172.16.1.0
        - 172.16.1.6
        - 172.16.0.30
      version: 2
      community: publiv
      name: system
      field:
        - name: hostname
          oid: .1.3.6.1.2.1.1.5.0
          is_tag: true
        - name: uptime
          oid: .1.3.6.1.2.1.1.3.0
        - name: sysObjectID
          oid: .1.3.6.1.2.1.1.2.0
      table:
        - name: interface_stats
          inherit_tags:
            - hostname
          field:
            - name: ifName
              oid: .1.3.6.1.2.1.31.1.1.1.1
              is_tag: true
      tags:
          deviceType: switch
          customer: me
```
gets me:
```
[inputs.snmp]
agents = ['172.16.1.0', '172.16.1.6', '172.16.0.30']
community = "publiv"
name = "system"
version = 2

  [[inputs.snmp.field]]
  is_tag = True
  name = "hostname"
  oid = ".1.3.6.1.2.1.1.5.0"

  [[inputs.snmp.field]]
  name = "uptime"
  oid = ".1.3.6.1.2.1.1.3.0"

  [[inputs.snmp.field]]
  name = "sysObjectID"
  oid = ".1.3.6.1.2.1.1.2.0"

  [[inputs.snmp.table]]
  inherit_tags = ['hostname']
  name = "interface_stats"

    [[field]]
    is_tag = True
    name = "ifName"
    oid = ".1.3.6.1.2.1.31.1.1.1.1"

  [inputs.snmp.tags]
  customer = "me"
  deviceType = "switch"
```

I can hack around `field` being incorrect by adding `inputs.snmp.table` to that level. However, `True` should be `true`.
